name: Generate Animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 

  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository to get access to the workflow files
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Generate a snake game from a GitHub user's contributions graph and output a SVG animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: bilal056
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # Push the generated SVG to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
